-- =====================================================================
-- Lot 2 — Référentiel des véhicules (schéma referentiel) — 07/10/2026
-- Modèle : document « Référentiel des véhicules — modèle (v1) », validé par Roger.
--   * schéma referentiel : terme_vehicule, terme_vehicule_genre, attribut_vehicule,
--     terme_vehicule_attribut, combinaison_categorie, usage_genre ;
--   * chargement depuis site.carrosseries, site.genres_etats,
--     site.carrosserie_usage_combinaisons et site.genres_usages, avec les corrections
--     décidées (voirie 10B, remorquage 06, tricycle/triporteur en « Usage commercial »,
--     tracteur agricole 10C, auto-école réservée au Minibus dans le transport en commun,
--     pas de 04A pour les bus, Camion/Minibus/Taxi de ville rattachés à leur genre, nouveaux termes) ;
--   * contrôle de cohérence combinaisons <-> usages ;
--   * les 4 tables de site deviennent des vues de mêmes noms et mêmes colonnes ;
--   * droits de lecture accordés au compte applicatif mutuellepro.
--
-- Usage :
--   essai à blanc : sudo -u postgres psql -d vpiclist -P pager=off -v ON_ERROR_STOP=1 -v commit=false -f /tmp/lot2_referentiel_vehicules.sql
--   application   : sudo -u postgres psql -d vpiclist -P pager=off -v ON_ERROR_STOP=1 -v commit=true  -f /tmp/lot2_referentiel_vehicules.sql
-- =====================================================================
\set QUIET on
\pset footer off
BEGIN;

\echo '=== 0. Garde-fous ==='
DO $g$
DECLARE n int; l text;
BEGIN
  IF to_regnamespace('referentiel') IS NOT NULL THEN RAISE EXCEPTION '[ÉCHEC]  le schéma referentiel existe déjà'; END IF;

  SELECT count(*), string_agg(DISTINCT c.genre_canonique, ', ') INTO n, l
    FROM site.carrosseries c LEFT JOIN tarification.genre g ON g.libelle = c.genre_canonique
   WHERE g.id_genre IS NULL;
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  genre(s) de carrosserie sans équivalent dans tarification.genre : %', l; END IF;

  SELECT count(*), string_agg(DISTINCT u.genre_canonique, ', ') INTO n, l
    FROM site.genres_usages u LEFT JOIN tarification.genre g ON g.libelle = u.genre_canonique
   WHERE g.id_genre IS NULL AND u.genre_canonique NOT IN ('Camion', 'Minibus', 'Taxi de ville');
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  genre(s) d usage inattendu(s) : %', l; END IF;

  SELECT count(*), string_agg(DISTINCT etat_nom, ', ') INTO n, l FROM site.genres_etats
   WHERE etat_nom NOT IN ('Tonnage', 'Remorque attachée', 'Double Cabine');
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  attribut(s) inattendu(s) : %', l; END IF;

  SELECT count(*), string_agg(code, ', ') INTO n, l
    FROM (SELECT code FROM site.usages_categories GROUP BY code HAVING count(*) > 1) d;
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  code(s) de catégorie en double : %', l; END IF;

  SELECT count(*), string_agg(n2.nspname || '.' || p.proname, ', ') INTO n, l
    FROM pg_proc p JOIN pg_namespace n2 ON n2.oid = p.pronamespace JOIN pg_language lg ON lg.oid = p.prolang
   WHERE lg.lanname <> 'c' AND n2.nspname NOT IN ('pg_catalog', 'information_schema')
     AND p.prosrc ~ '\m(carrosseries|genres_etats|carrosserie_usage_combinaisons|genres_usages)\M';
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  fonction(s) lisant les tables remplacées : %', l; END IF;

  RAISE NOTICE '[OK]     Genres reconnus, codes de catégorie uniques, aucune fonction concernée';
END $g$;

\echo '=== 1. Ce que reçoit le devis AVANT (mêmes requêtes que server.js) ==='
CREATE TEMP TABLE _api_avant AS
SELECT 'carrosseries' AS jeu, row_to_json(x)::text AS ligne FROM (SELECT nom, genre_canonique FROM site.carrosseries WHERE actif = true) x
UNION ALL SELECT 'genres_etats', row_to_json(x)::text FROM (SELECT alias, etat_nom, etat_options FROM site.genres_etats WHERE actif = true) x
UNION ALL SELECT 'genres_usages', row_to_json(x)::text FROM (SELECT genre_canonique, usage_libelle, code_categorie FROM site.genres_usages WHERE actif = true) x
UNION ALL SELECT 'combinaisons', row_to_json(x)::text FROM (SELECT carrosserie, double_commande, matiere_inflammable, codes_categorie FROM site.carrosserie_usage_combinaisons WHERE actif = true) x;
SELECT jeu, count(*) AS lignes FROM _api_avant GROUP BY jeu ORDER BY jeu;

\echo '=== 2. Schéma et tables du référentiel ==='
ALTER TABLE site.usages_categories ADD CONSTRAINT usages_categories_code_key UNIQUE (code);

CREATE SCHEMA referentiel;
COMMENT ON SCHEMA referentiel IS 'Nomenclatures partagées par tous les domaines (lot 2, 07/10/2026).';

CREATE TABLE referentiel.terme_vehicule (
  id_terme_vehicule      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle                varchar(100) NOT NULL UNIQUE,
  id_genre               integer NOT NULL REFERENCES tarification.genre (id_genre),
  code_categorie_imposee varchar(10) REFERENCES site.usages_categories (code),
  actif                  boolean NOT NULL DEFAULT true,
  ordre_affichage        integer NOT NULL DEFAULT 0
);
COMMENT ON TABLE referentiel.terme_vehicule IS 'Lexique des types de véhicules : forme du véhicule, genre canonique principal, catégorie imposée pour un terme directif.';

CREATE TABLE referentiel.terme_vehicule_genre (
  id_terme_vehicule_genre integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_terme_vehicule       integer NOT NULL REFERENCES referentiel.terme_vehicule (id_terme_vehicule),
  id_genre                integer NOT NULL REFERENCES tarification.genre (id_genre),
  code_categorie_defaut   varchar(10) REFERENCES site.usages_categories (code),
  UNIQUE (id_terme_vehicule, id_genre)
);
COMMENT ON TABLE referentiel.terme_vehicule_genre IS 'Genres d un terme qui en a plusieurs (porte-véhicules), avec la catégorie par défaut de chaque couple.';

CREATE TABLE referentiel.attribut_vehicule (
  code_attribut_vehicule varchar(30) PRIMARY KEY,
  libelle                varchar(50) NOT NULL UNIQUE,
  valeurs                jsonb NOT NULL
);
COMMENT ON TABLE referentiel.attribut_vehicule IS 'Attributs d un véhicule et leurs valeurs possibles.';

CREATE TABLE referentiel.terme_vehicule_attribut (
  id_terme_vehicule_attribut integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_terme_vehicule          integer NOT NULL REFERENCES referentiel.terme_vehicule (id_terme_vehicule),
  code_attribut_vehicule     varchar(30) NOT NULL REFERENCES referentiel.attribut_vehicule (code_attribut_vehicule),
  actif                      boolean NOT NULL DEFAULT true,
  ordre_affichage            integer NOT NULL DEFAULT 0,
  UNIQUE (id_terme_vehicule, code_attribut_vehicule)
);

CREATE TABLE referentiel.combinaison_categorie (
  id_combinaison_categorie integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_terme_vehicule        integer NOT NULL REFERENCES referentiel.terme_vehicule (id_terme_vehicule),
  double_commande          varchar(10) CHECK (double_commande IN ('Avec', 'Sans')),
  matiere_inflammable      varchar(10) CHECK (matiere_inflammable IN ('Oui', 'Non')),
  code_categorie           varchar(10) REFERENCES site.usages_categories (code),
  actif                    boolean NOT NULL DEFAULT true,
  ordre_affichage          integer NOT NULL DEFAULT 0,
  UNIQUE NULLS NOT DISTINCT (id_terme_vehicule, double_commande, matiere_inflammable, code_categorie)
);
COMMENT ON TABLE referentiel.combinaison_categorie IS 'Catégories autorisées pour un terme selon la double commande et la matière inflammable ; code vide = aucune catégorie possible.';

CREATE TABLE referentiel.usage_genre (
  id_usage_genre  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_genre        integer NOT NULL REFERENCES tarification.genre (id_genre),
  libelle_usage   varchar(200) NOT NULL,
  code_categorie  varchar(10) NOT NULL REFERENCES site.usages_categories (code),
  actif           boolean NOT NULL DEFAULT true,
  ordre_affichage integer NOT NULL DEFAULT 0,
  UNIQUE (id_genre, libelle_usage, code_categorie)
);
COMMENT ON TABLE referentiel.usage_genre IS 'Libellés d usage proposés à l utilisateur pour un genre, avec leur catégorie.';

\echo '=== 3. Lexique ==='
INSERT INTO referentiel.terme_vehicule (id_terme_vehicule, libelle, id_genre, code_categorie_imposee, actif, ordre_affichage)
SELECT c.id, c.nom, g.id_genre, CASE WHEN c.nom = 'Taxi' THEN '04A' END, c.actif, c.ordre_affichage
  FROM site.carrosseries c
  JOIN tarification.genre g
    ON g.libelle = CASE WHEN c.nom = 'Voirie' THEN 'Véhicule de collectivité locale' ELSE c.genre_canonique END;

-- recaler l'identité après les identifiants repris de site.carrosseries
SELECT setval(pg_get_serial_sequence('referentiel.terme_vehicule', 'id_terme_vehicule'),
              (SELECT max(id_terme_vehicule) FROM referentiel.terme_vehicule));

INSERT INTO referentiel.terme_vehicule (libelle, id_genre, code_categorie_imposee, ordre_affichage)
SELECT v.libelle, g.id_genre, v.imposee, v.ordre
  FROM (VALUES
    ('Moto-taxi',                  'Motocyclette',                    '05bis', 101),
    ('Remorque',                   'Remorque',                        NULL,    110),
    ('Remorque frigorifique',      'Remorque',                        NULL,    111),
    ('Plateau',                    'Remorque',                        NULL,    112),
    ('Porte-grumes',               'Remorque',                        NULL,    113),
    ('Porte-billes',               'Remorque',                        NULL,    114),
    ('Savoyarde',                  'Remorque',                        NULL,    115),
    ('Bétaillère',                 'Remorque',                        NULL,    116),
    ('Bagagère',                   'Remorque',                        NULL,    117),
    ('Porte-bateau',               'Remorque',                        NULL,    118),
    ('Caravane',                   'Remorque',                        NULL,    119),
    ('Dolly',                      'Remorque',                        NULL,    120),
    ('Attelage',                   'Remorque',                        NULL,    121),
    ('Semi-remorque frigorifique', 'Semi-remorque',                   NULL,    130),
    ('Porte-véhicules',            'Véhicule utilitaire',             NULL,    140),
    ('Porte-engin',                'Engin spécial',                   NULL,    150),
    ('Roulotte de chantier',       'Engin spécial',                   NULL,    151),
    ('Remorque agricole',          'Tracteur agricole ou forestier',  NULL,    160)
  ) v(libelle, genre, imposee, ordre)
  JOIN tarification.genre g ON g.libelle = v.genre;


INSERT INTO referentiel.terme_vehicule_genre (id_terme_vehicule, id_genre, code_categorie_defaut)
SELECT t.id_terme_vehicule, g.id_genre, v.defaut
  FROM (VALUES ('Véhicule utilitaire', '06'), ('Véhicule de remorquage', '06'), ('Véhicule de collectivité locale', '10B')) v(genre, defaut)
  JOIN tarification.genre g ON g.libelle = v.genre
  JOIN referentiel.terme_vehicule t ON t.libelle = 'Porte-véhicules';

\echo '=== 4. Attributs ==='
INSERT INTO referentiel.attribut_vehicule (code_attribut_vehicule, libelle, valeurs) VALUES
  ('TONNAGE',             'Tonnage',             '["Léger (< 3,5 t)", "Lourd (> 3,5 t)"]'),
  ('REMORQUE_ATTACHEE',   'Remorque attachée',   '["Avec", "Sans"]'),
  ('DOUBLE_CABINE',       'Double cabine',       '["Avec", "Sans"]'),
  ('DOUBLE_COMMANDE',     'Double commande',     '["Avec", "Sans"]'),
  ('MATIERE_INFLAMMABLE', 'Matière inflammable', '["Oui", "Non"]');

INSERT INTO referentiel.terme_vehicule_attribut (id_terme_vehicule_attribut, id_terme_vehicule, code_attribut_vehicule, actif, ordre_affichage)
SELECT e.id, t.id_terme_vehicule,
       CASE e.etat_nom WHEN 'Tonnage' THEN 'TONNAGE' WHEN 'Remorque attachée' THEN 'REMORQUE_ATTACHEE' ELSE 'DOUBLE_CABINE' END,
       e.actif, e.ordre_affichage
  FROM site.genres_etats e JOIN referentiel.terme_vehicule t ON t.libelle = e.alias;

-- recaler l'identité après les identifiants repris de site.genres_etats
SELECT setval(pg_get_serial_sequence('referentiel.terme_vehicule_attribut', 'id_terme_vehicule_attribut'),
              (SELECT max(id_terme_vehicule_attribut) FROM referentiel.terme_vehicule_attribut));

INSERT INTO referentiel.terme_vehicule_attribut (id_terme_vehicule, code_attribut_vehicule, ordre_affichage)
SELECT t.id_terme_vehicule, 'TONNAGE', 1 FROM referentiel.terme_vehicule t
 WHERE t.libelle IN ('Remorque', 'Remorque frigorifique', 'Plateau', 'Porte-grumes', 'Porte-billes', 'Savoyarde',
                     'Bétaillère', 'Bagagère', 'Porte-bateau', 'Caravane', 'Dolly', 'Attelage',
                     'Semi-remorque frigorifique', 'Porte-véhicules', 'Porte-engin', 'Roulotte de chantier', 'Remorque agricole');


\echo '=== 5. Combinaisons de catégories ==='
INSERT INTO referentiel.combinaison_categorie (id_terme_vehicule, double_commande, matiere_inflammable, code_categorie, actif, ordre_affichage)
SELECT t.id_terme_vehicule, nullif(btrim(c.double_commande), ''), nullif(btrim(c.matiere_inflammable), ''),
       x.code, c.actif, c.ordre_affichage
  FROM site.carrosserie_usage_combinaisons c
  JOIN referentiel.terme_vehicule t ON t.libelle = c.carrosserie
  LEFT JOIN LATERAL jsonb_array_elements_text(c.codes_categorie) x(code) ON true;

INSERT INTO referentiel.combinaison_categorie (id_terme_vehicule, code_categorie, ordre_affichage)
SELECT t.id_terme_vehicule, v.code, 100
  FROM (VALUES
    ('Moto-taxi', '05bis'),
    ('Remorque', '01'), ('Remorque', '02'), ('Remorque', '03'),
    ('Remorque frigorifique', '01'), ('Remorque frigorifique', '02'), ('Remorque frigorifique', '03'),
    ('Plateau', '01'), ('Plateau', '02'), ('Plateau', '03'),
    ('Porte-grumes', '01'), ('Porte-grumes', '02'), ('Porte-grumes', '03'),
    ('Porte-billes', '01'), ('Porte-billes', '02'), ('Porte-billes', '03'),
    ('Savoyarde', '01'), ('Savoyarde', '02'), ('Savoyarde', '03'),
    ('Bétaillère', '01'), ('Bétaillère', '02'), ('Bétaillère', '03'),
    ('Bagagère', '01'), ('Bagagère', '02'), ('Bagagère', '03'),
    ('Porte-bateau', '01'), ('Porte-bateau', '02'), ('Porte-bateau', '03'),
    ('Caravane', '01'), ('Caravane', '02'), ('Caravane', '03'),
    ('Dolly', '01'), ('Dolly', '02'), ('Dolly', '03'),
    ('Attelage', '01'), ('Attelage', '02'), ('Attelage', '03'),
    ('Semi-remorque frigorifique', '02'), ('Semi-remorque frigorifique', '03'),
    ('Porte-véhicules', '06'), ('Porte-véhicules', '10B'),
    ('Porte-engin', '09B'), ('Roulotte de chantier', '09B'),
    ('Remorque agricole', '10C')
  ) v(terme, code)
  JOIN referentiel.terme_vehicule t ON t.libelle = v.terme;

-- Décision du 07/10/2026 : seul le Minibus peut servir à l'auto-école dans le transport en commun.
DELETE FROM referentiel.combinaison_categorie c
 USING referentiel.terme_vehicule t
 WHERE t.id_terme_vehicule = c.id_terme_vehicule
   AND t.libelle IN ('Autobus', 'Autocar', 'Bus', 'Car')
   AND c.code_categorie IN ('07ARC', '07SRC');
-- La combinaison « avec double commande » reste présente, sans aucune catégorie possible.
INSERT INTO referentiel.combinaison_categorie (id_terme_vehicule, double_commande, matiere_inflammable, code_categorie, ordre_affichage)
SELECT t.id_terme_vehicule, 'Avec', NULL, NULL, min(t.ordre_affichage)
  FROM referentiel.terme_vehicule t
 WHERE t.libelle IN ('Autobus', 'Autocar', 'Bus', 'Car')
   AND NOT EXISTS (SELECT 1 FROM referentiel.combinaison_categorie c
                    WHERE c.id_terme_vehicule = t.id_terme_vehicule AND c.double_commande = 'Avec')
 GROUP BY t.id_terme_vehicule;

\echo '=== 6. Usages par genre ==='
CREATE TEMP TABLE _ug AS
SELECT u.id, u.ordre_affichage, u.actif,
       CASE u.genre_canonique
         WHEN 'Camion'        THEN CASE WHEN u.usage_libelle = 'Voirie et entretien municipal'
                                        THEN 'Véhicule de collectivité locale' ELSE 'Véhicule utilitaire' END
         WHEN 'Minibus'       THEN 'Véhicule de transport en commun'
         WHEN 'Taxi de ville' THEN 'Véhicule de tourisme'
         ELSE u.genre_canonique END AS genre,
       CASE WHEN u.genre_canonique = 'Tracteur agricole ou forestier' AND u.code_categorie = '10C' THEN 'Travaux agricoles et forestiers'
            WHEN u.genre_canonique IN ('Tricycle', 'Triporteur') AND u.code_categorie = '05bis' THEN 'Usage commercial'
            ELSE u.usage_libelle END AS libelle_usage,
       CASE WHEN u.usage_libelle = 'Voirie et entretien municipal' THEN '10B'
            ELSE u.code_categorie END AS code_categorie
  FROM site.genres_usages u
 WHERE NOT (u.genre_canonique IN ('Tricycle', 'Triporteur') AND u.code_categorie IN ('01', '02', '03'))
   AND NOT (u.genre_canonique = 'Tracteur agricole ou forestier' AND u.code_categorie IN ('09', '03'))
   -- doublons et corrections décidés le 07/10/2026
   AND u.genre_canonique <> 'Taxi de ville'                                            -- remplacé par « Transport urbain payant » (tourisme, 04A)
   AND NOT (u.genre_canonique = 'Véhicule de remorquage' AND u.code_categorie = '10B') -- remplacé par « Essai / Garage / Remorquage » (06)
   AND NOT (u.genre_canonique = 'Véhicule utilitaire' AND u.code_categorie = '10B')    -- la voirie relève de la collectivité locale
   AND NOT (u.genre_canonique = 'Véhicule de transport en commun' AND u.code_categorie = '04A'); -- pas de tarif 04A pour les bus (à rouvrir plus tard)

INSERT INTO _ug (id, ordre_affichage, actif, genre, libelle_usage, code_categorie)
SELECT NULL, v.ordre, true, v.genre, v.libelle, v.code
  FROM (VALUES
    ('Véhicule utilitaire', 'Auto-école sans RC élèves', '07SRC', 8),
    ('Tricycle',   'Essai (véhicule non encore mis en circulation commerciale)', '06', 91),
    ('Tricycle',   'Non circulation prolongée (garage)', '06', 92),
    ('Tricycle',   'Auto-école avec RC élèves', '07ARC', 93),
    ('Tricycle',   'Auto-école sans RC élèves', '07SRC', 94),
    ('Triporteur', 'Essai (véhicule non encore mis en circulation commerciale)', '06', 91),
    ('Triporteur', 'Non circulation prolongée (garage)', '06', 92),
    ('Triporteur', 'Auto-école avec RC élèves', '07ARC', 93),
    ('Triporteur', 'Auto-école sans RC élèves', '07SRC', 94)
  ) v(genre, libelle, code, ordre);

INSERT INTO referentiel.usage_genre (id_genre, libelle_usage, code_categorie, actif, ordre_affichage)
SELECT DISTINCT ON (g.id_genre, u.libelle_usage, u.code_categorie)
       g.id_genre, u.libelle_usage, u.code_categorie, u.actif, u.ordre_affichage
  FROM _ug u JOIN tarification.genre g ON g.libelle = u.genre
 ORDER BY g.id_genre, u.libelle_usage, u.code_categorie, u.ordre_affichage, u.id NULLS LAST;

\echo '=== 7. Contrôle de cohérence combinaisons <-> usages ==='
CREATE TEMP TABLE _genres_terme AS
SELECT id_terme_vehicule, id_genre FROM referentiel.terme_vehicule
UNION SELECT id_terme_vehicule, id_genre FROM referentiel.terme_vehicule_genre;

DO $c$
DECLARE n int; l text;
BEGIN
  SELECT count(*), string_agg(t.libelle || ' : ' || c.code_categorie, ', ') INTO n, l
    FROM referentiel.combinaison_categorie c
    JOIN referentiel.terme_vehicule t USING (id_terme_vehicule)
   WHERE c.code_categorie IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM _genres_terme gt JOIN referentiel.usage_genre u ON u.id_genre = gt.id_genre
                      WHERE gt.id_terme_vehicule = c.id_terme_vehicule AND u.code_categorie = c.code_categorie);
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  catégorie(s) autorisée(s) sans usage proposé : %', l; END IF;

  SELECT count(*), string_agg(g.libelle || ' : ' || u.code_categorie, ', ') INTO n, l
    FROM referentiel.usage_genre u JOIN tarification.genre g USING (id_genre)
   WHERE NOT EXISTS (SELECT 1 FROM _genres_terme gt JOIN referentiel.combinaison_categorie c USING (id_terme_vehicule)
                      WHERE gt.id_genre = u.id_genre AND c.code_categorie = u.code_categorie);
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  usage(s) proposé(s) sans catégorie autorisée : %', l; END IF;

  SELECT count(*), string_agg(t.libelle, ', ') INTO n, l FROM referentiel.terme_vehicule t
   WHERE NOT EXISTS (SELECT 1 FROM referentiel.combinaison_categorie c WHERE c.id_terme_vehicule = t.id_terme_vehicule);
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  terme(s) sans aucune combinaison : %', l; END IF;

  RAISE NOTICE '[OK]     Combinaisons et usages cohérents dans les deux sens ; chaque terme a ses combinaisons';
END $c$;

SELECT 'termes' AS objet, count(*) AS nb FROM referentiel.terme_vehicule
UNION ALL SELECT 'genres supplémentaires', count(*) FROM referentiel.terme_vehicule_genre
UNION ALL SELECT 'attributs de termes', count(*) FROM referentiel.terme_vehicule_attribut
UNION ALL SELECT 'combinaisons', count(*) FROM referentiel.combinaison_categorie
UNION ALL SELECT 'usages', count(*) FROM referentiel.usage_genre;

\echo '=== 8. Les tables de site deviennent des vues de compatibilité ==='
DROP TABLE site.genres_etats;
DROP TABLE site.carrosserie_usage_combinaisons;
DROP TABLE site.genres_usages;
DROP TABLE site.carrosseries;

CREATE VIEW site.carrosseries AS
SELECT t.id_terme_vehicule AS id, t.libelle AS nom, g.libelle AS genre_canonique, t.actif, t.ordre_affichage
  FROM referentiel.terme_vehicule t JOIN tarification.genre g USING (id_genre);

CREATE VIEW site.genres_etats AS
SELECT ta.id_terme_vehicule_attribut AS id, t.libelle AS alias, a.libelle AS etat_nom, a.valeurs AS etat_options,
       ta.actif, ta.ordre_affichage
  FROM referentiel.terme_vehicule_attribut ta
  JOIN referentiel.terme_vehicule t USING (id_terme_vehicule)
  JOIN referentiel.attribut_vehicule a USING (code_attribut_vehicule);

CREATE VIEW site.carrosserie_usage_combinaisons AS
SELECT min(c.id_combinaison_categorie) AS id, t.libelle AS carrosserie, c.double_commande, c.matiere_inflammable,
       jsonb_agg(c.code_categorie ORDER BY c.code_categorie) FILTER (WHERE c.code_categorie IS NOT NULL) AS codes_categorie,
       bool_and(c.actif) AS actif, min(c.ordre_affichage) AS ordre_affichage
  FROM referentiel.combinaison_categorie c JOIN referentiel.terme_vehicule t USING (id_terme_vehicule)
 GROUP BY t.libelle, c.double_commande, c.matiere_inflammable;

CREATE VIEW site.genres_usages AS
SELECT u.id_usage_genre AS id, g.libelle AS genre_canonique, u.libelle_usage AS usage_libelle, u.code_categorie,
       u.ordre_affichage, u.actif
  FROM referentiel.usage_genre u JOIN tarification.genre g USING (id_genre);

COMMENT ON VIEW site.carrosseries IS 'COMPATIBILITÉ (lot 2) : lecture du lexique referentiel.terme_vehicule pour le devis.';
COMMENT ON VIEW site.genres_etats IS 'COMPATIBILITÉ (lot 2) : lecture de referentiel.terme_vehicule_attribut.';
COMMENT ON VIEW site.carrosserie_usage_combinaisons IS 'COMPATIBILITÉ (lot 2) : lecture de referentiel.combinaison_categorie.';
COMMENT ON VIEW site.genres_usages IS 'COMPATIBILITÉ (lot 2) : lecture de referentiel.usage_genre.';

\echo '=== 9. Droits de lecture du compte applicatif ==='
GRANT USAGE ON SCHEMA referentiel TO mutuellepro;
GRANT SELECT ON ALL TABLES IN SCHEMA referentiel TO mutuellepro;
GRANT SELECT ON site.carrosseries, site.genres_etats, site.carrosserie_usage_combinaisons, site.genres_usages TO mutuellepro;
DO $d$
BEGIN
  IF NOT has_table_privilege('mutuellepro', 'site.carrosseries', 'SELECT')
     OR NOT has_table_privilege('mutuellepro', 'site.genres_usages', 'SELECT')
     OR NOT has_table_privilege('mutuellepro', 'referentiel.terme_vehicule', 'SELECT') THEN
    RAISE EXCEPTION '[ÉCHEC]  droits de lecture manquants pour mutuellepro';
  END IF;
  RAISE NOTICE '[OK]     Droits de lecture accordés à mutuellepro';
END $d$;

\echo '=== 10. Ce que reçoit le devis APRÈS : différences (seules les corrections décidées doivent apparaître) ==='
CREATE TEMP TABLE _api_apres AS
SELECT 'carrosseries' AS jeu, row_to_json(x)::text AS ligne FROM (SELECT nom, genre_canonique FROM site.carrosseries WHERE actif = true) x
UNION ALL SELECT 'genres_etats', row_to_json(x)::text FROM (SELECT alias, etat_nom, etat_options FROM site.genres_etats WHERE actif = true) x
UNION ALL SELECT 'genres_usages', row_to_json(x)::text FROM (SELECT genre_canonique, usage_libelle, code_categorie FROM site.genres_usages WHERE actif = true) x
UNION ALL SELECT 'combinaisons', row_to_json(x)::text FROM (SELECT carrosserie, double_commande, matiere_inflammable, codes_categorie FROM site.carrosserie_usage_combinaisons WHERE actif = true) x;

SELECT 'retiré' AS sens, jeu, ligne FROM (SELECT * FROM _api_avant EXCEPT SELECT * FROM _api_apres) a
UNION ALL
SELECT 'ajouté', jeu, ligne FROM (SELECT * FROM _api_apres EXCEPT SELECT * FROM _api_avant) b
ORDER BY jeu, ligne, sens DESC;

\echo '=== Fin ==='
\if :commit
  COMMIT;
  \echo '>>> VALIDÉ : référentiel des véhicules en place.'
\else
  ROLLBACK;
  \echo '>>> ESSAI À BLANC : tout a été annulé. Relancer avec -v commit=true pour appliquer.'
\endif
