-- =====================================================================
-- Lot 3 — Rattachement du catalogue au lexique des véhicules (07/10/2026)
--   * usage « (aucune précision nécessaire) » de la collectivité locale renommé ;
--   * referentiel.fn_normaliser_libelle + referentiel.correspondance_libelle_vehicule
--     (67 libellés d'agences -> terme, attributs, catégorie suggérée, validés par Roger) ;
--   * catalogue.vehicule_catalogue : id_terme_vehicule, avec_remorque, avec_double_commande,
--     avec_double_cabine, code_categorie_suggeree ; fusion des doublons ; colonne genre supprimée ;
--   * vue catalogue.profil_vehicule (lue par l'API) ; vue transitoire vehicules_catalogue recréée ;
--   * droits de lecture pour mutuellepro.
--
-- Usage :
--   essai à blanc : sudo -u postgres psql -d vpiclist -P pager=off -v ON_ERROR_STOP=1 -v commit=false -f /tmp/lot3_catalogue_lexique.sql
--   application   : sudo -u postgres psql -d vpiclist -P pager=off -v ON_ERROR_STOP=1 -v commit=true  -f /tmp/lot3_catalogue_lexique.sql
-- =====================================================================
\set QUIET on
\pset footer off
BEGIN;

\echo '=== 0. État initial ==='
CREATE TEMP TABLE _volumes_avant AS
SELECT (SELECT count(*) FROM catalogue.vehicule_catalogue) AS profils,
       (SELECT count(*) FROM catalogue.vehicule_source)    AS sources,
       (SELECT count(*) FROM catalogue.anomalie_fusion)    AS anomalies;
SELECT * FROM _volumes_avant;

\echo '=== 1. Usage de la collectivité locale ==='
UPDATE referentiel.usage_genre u SET libelle_usage = 'Véhicule de collectivité locale'
  FROM tarification.genre g
 WHERE g.id_genre = u.id_genre AND g.libelle = 'Véhicule de collectivité locale'
   AND u.libelle_usage = '(aucune précision nécessaire)';

\echo '=== 2. Correspondance des libellés d agences ==='
CREATE FUNCTION referentiel.fn_normaliser_libelle(p_libelle text) RETURNS text
LANGUAGE sql IMMUTABLE AS $f$
  SELECT btrim(regexp_replace(regexp_replace(
           translate(lower(coalesce(p_libelle, '')), 'àâäéèêëîïôöùûüç', 'aaaeeeeiioouuuc'),
           '\d+\s*places?', '', 'g'),
           '\s+', ' ', 'g'))
$f$;
COMMENT ON FUNCTION referentiel.fn_normaliser_libelle(text) IS
  'Clé de rapprochement d un libellé : minuscules, sans accents, espaces réduits.';

CREATE TABLE referentiel.correspondance_libelle_vehicule (
  id_correspondance_libelle_vehicule integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle_source          varchar(200) NOT NULL,
  cle_normalisee          varchar(200) NOT NULL UNIQUE,
  id_terme_vehicule       integer NOT NULL REFERENCES referentiel.terme_vehicule (id_terme_vehicule),
  avec_remorque           boolean NOT NULL DEFAULT false,
  avec_double_commande    boolean NOT NULL DEFAULT false,
  avec_double_cabine      boolean NOT NULL DEFAULT false,
  code_categorie_suggeree varchar(10) REFERENCES site.usages_categories (code)
);
COMMENT ON TABLE referentiel.correspondance_libelle_vehicule IS
  'Libellés de genre des fichiers d agences -> terme du lexique, attributs et catégorie suggérée (import du catalogue).';

INSERT INTO referentiel.correspondance_libelle_vehicule
  (libelle_source, cle_normalisee, id_terme_vehicule, avec_remorque, avec_double_commande, avec_double_cabine, code_categorie_suggeree)
SELECT v.libelle, referentiel.fn_normaliser_libelle(v.libelle), t.id_terme_vehicule, v.rem, v.dco, v.cab, v.cat
  FROM (VALUES
    ('V.P.', 'Véhicule de tourisme', false, false, false, '01'),
    ('Taxi De Ville', 'Taxi', false, false, false, '04A'),
    ('Tourisme', 'Véhicule de tourisme', false, false, false, '01'),
    ('Motocyclette', 'Motocyclette', false, false, false, '05'),
    ('Camionnette', 'Camionnette', false, false, false, '02'),
    ('V.T.', 'Véhicule de tourisme', false, false, false, '01'),
    ('Camion', 'Camion', false, false, false, '03'),
    ('Pick-Up', 'Pick-up', false, false, false, '02'),
    ('V.U. <3.5', 'Véhicule utilitaire', false, false, false, '02'),
    ('Fourgonnette', 'Fourgonnette', false, false, false, '02'),
    ('Moto Taxi', 'Moto-taxi', false, false, false, '05bis'),
    ('Fourgon', 'Fourgon', false, false, false, '03'),
    ('Minibus', 'Minibus', false, false, false, '04B'),
    ('Autocar', 'Autocar', false, false, false, '04B'),
    ('Camion (Usage 02)', 'Camion', false, false, false, '02'),
    ('Tricycle', 'Tricycle', false, false, false, '05'),
    ('C.I.', 'Conduite intérieure', false, false, false, '01'),
    ('Bachée', 'Bâchée', false, false, false, '02'),
    ('Bus', 'Bus', false, false, false, '04B'),
    ('Camionnette /Dc', 'Camionnette', false, false, true, '02'),
    ('Car', 'Car', false, false, false, '04B'),
    ('Tracteur (Camion)', 'Camion Tracteur', false, false, false, '03'),
    ('Auto Ecole Dco (Catégorie I)', 'Véhicule de tourisme', false, true, false, '07SRC'),
    ('Semi-Remorque', 'Semi-remorque', false, false, false, '03'),
    ('Corbillard', 'Corbillard', false, false, false, '10A'),
    ('Remorque', 'Remorque', false, false, false, '03'),
    ('Fourgon (Usage 02)', 'Fourgon', false, false, false, '02'),
    ('Camion Tracteur', 'Camion Tracteur', false, false, false, '03'),
    ('V.U. >3.5 (Usage 02)', 'Véhicule utilitaire', false, false, false, '02'),
    ('Engin De Chantier', 'Engin spécial', false, false, false, '09B'),
    ('Camionette (Usage 03)', 'Camionnette', false, false, false, '03'),
    ('Camion Benne', 'Camion Benne', false, false, false, '03'),
    ('Autobus', 'Autobus', false, false, false, '04B'),
    ('Ambulance', 'Ambulance', false, false, false, '10A'),
    ('V.U. >3.5', 'Véhicule utilitaire', false, false, false, '03'),
    ('Tracteur (Camion) (Usage 02)', 'Camion Tracteur', false, false, false, '02'),
    ('Conduites Intérieure 5 Portes', 'Conduite intérieure', false, false, false, '01'),
    ('Auto Ecole Sco (Catégorie I)', 'Véhicule de tourisme', false, false, false, '07SRC'),
    ('Semi-Remorque (Usage 02)', 'Semi-remorque', false, false, false, '02'),
    ('Camion Citerne', 'Camion Citerne', false, false, false, '03'),
    ('Engin Grands Travaux', 'Engin spécial', false, false, false, '09B'),
    ('Break', 'Break', false, false, false, '01'),
    ('Auto Location (V.P.)', 'Véhicule de tourisme', false, false, false, '08'),
    ('Tourisme + Remorque', 'Véhicule de tourisme', true, false, false, '01'),
    ('Voirie Truck (Usage 10 A)', 'Voirie', false, false, false, '10B'),
    ('Pick-Up /Dc', 'Pick-up', false, false, true, '02'),
    ('Motocyclette + Remorque', 'Motocyclette', true, false, false, '05'),
    ('Fourgon /Dc (Usage 02)', 'Fourgon', false, false, true, '02'),
    ('Fourgonnette (Usage 03)', 'Fourgonnette', false, false, false, '03'),
    ('Camion Benne (Usage 02)', 'Camion Benne', false, false, false, '02'),
    ('Garage (V.P.)', 'Véhicule de tourisme', false, false, false, '06'),
    ('Auto Ecole Dco (Catégorie Ii)', 'Véhicule utilitaire', false, true, false, '07SRC'),
    ('Scooter', 'Scooter', false, false, false, '05'),
    ('Tracteur + Remorque', 'Camion Tracteur', true, false, false, '03'),
    ('Engin Grands Travaux + Remorque', 'Engin spécial', true, false, false, '09B'),
    ('Remorque (Usage 02)', 'Remorque', false, false, false, '02'),
    ('Moto En Éssai', 'Motocyclette', false, false, false, '06'),
    ('V.P. + Remorque', 'Véhicule de tourisme', true, false, false, '01'),
    ('Citerne', 'Citerne', false, false, false, '03'),
    ('V.U. Remorque (Usage 06)', 'Véhicule utilitaire', true, false, false, '06'),
    ('Auto Ecole Scooter (Catégorie V)', 'Scooter', false, false, false, '07SRC'),
    ('Engin Manutention', 'Engin spécial', false, false, false, '09A')
  ) v(libelle, terme, rem, dco, cab, cat)
  JOIN referentiel.terme_vehicule t ON t.libelle = v.terme;

DO $c$
DECLARE n int; l text;
BEGIN
  IF (SELECT count(*) FROM referentiel.correspondance_libelle_vehicule) <> 62 THEN
    RAISE EXCEPTION '[ÉCHEC]  % libellé(s) chargé(s) au lieu de 62 (terme introuvable ?)',
      (SELECT count(*) FROM referentiel.correspondance_libelle_vehicule);
  END IF;
  -- la catégorie suggérée doit être autorisée par les combinaisons du terme
  SELECT count(*), string_agg(c.libelle_source || ' -> ' || c.code_categorie_suggeree, ', ') INTO n, l
    FROM referentiel.correspondance_libelle_vehicule c
   WHERE c.code_categorie_suggeree IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM referentiel.combinaison_categorie k
                      WHERE k.id_terme_vehicule = c.id_terme_vehicule
                        AND k.code_categorie = c.code_categorie_suggeree
                        AND (k.double_commande IS NULL
                             OR k.double_commande = CASE WHEN c.avec_double_commande THEN 'Avec' ELSE 'Sans' END));
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  catégorie suggérée non autorisée : %', l; END IF;
  -- un terme directif impose sa catégorie
  SELECT count(*), string_agg(c.libelle_source, ', ') INTO n, l
    FROM referentiel.correspondance_libelle_vehicule c JOIN referentiel.terme_vehicule t USING (id_terme_vehicule)
   WHERE t.code_categorie_imposee IS NOT NULL AND c.code_categorie_suggeree IS DISTINCT FROM t.code_categorie_imposee;
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  catégorie contraire au terme directif : %', l; END IF;
  -- tous les libellés présents dans le catalogue sont couverts
  SELECT count(*), string_agg(DISTINCT v.genre, ', ') INTO n, l
    FROM catalogue.vehicule_catalogue v
   WHERE NOT EXISTS (SELECT 1 FROM referentiel.correspondance_libelle_vehicule c
                      WHERE c.cle_normalisee = referentiel.fn_normaliser_libelle(v.genre));
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  % profil(s) au libellé non couvert : %', n, l; END IF;
  RAISE NOTICE '[OK]     62 libellés, catégories autorisées, tous les profils couverts';
END $c$;

\echo '=== 3. Rattachement du catalogue ==='
ALTER TABLE catalogue.vehicule_catalogue
  ADD COLUMN id_terme_vehicule       integer REFERENCES referentiel.terme_vehicule (id_terme_vehicule),
  ADD COLUMN avec_remorque           boolean NOT NULL DEFAULT false,
  ADD COLUMN avec_double_commande    boolean NOT NULL DEFAULT false,
  ADD COLUMN avec_double_cabine      boolean NOT NULL DEFAULT false,
  ADD COLUMN code_categorie_suggeree varchar(10) REFERENCES site.usages_categories (code);

UPDATE catalogue.vehicule_catalogue v
   SET id_terme_vehicule = c.id_terme_vehicule, avec_remorque = c.avec_remorque,
       avec_double_commande = c.avec_double_commande, avec_double_cabine = c.avec_double_cabine,
       code_categorie_suggeree = c.code_categorie_suggeree
  FROM referentiel.correspondance_libelle_vehicule c
 WHERE c.cle_normalisee = referentiel.fn_normaliser_libelle(v.genre);

\echo '--- Répartition par terme ---'
SELECT t.libelle AS terme, count(*) AS profils
  FROM catalogue.vehicule_catalogue v JOIN referentiel.terme_vehicule t USING (id_terme_vehicule)
 GROUP BY t.libelle ORDER BY profils DESC;

\echo '=== 4. Fusion des profils devenus identiques ==='
CREATE TEMP TABLE _fusion AS
SELECT id_vehicule_catalogue AS id_doublon, id_conserve FROM (
  SELECT id_vehicule_catalogue,
         min(id_vehicule_catalogue) OVER (PARTITION BY vin, marque, modele, id_terme_vehicule, avec_remorque,
                                          avec_double_commande, avec_double_cabine, code_categorie_suggeree,
                                          energie, puissance, charge_utile, nombre_places) AS id_conserve
    FROM catalogue.vehicule_catalogue) x
 WHERE id_vehicule_catalogue <> id_conserve;
SELECT count(*) AS doublons_fusionnes FROM _fusion;

INSERT INTO catalogue.anomalie_fusion
  (vin, site_origine, id_reference, champ, valeur_catalogue, valeur_nouvelle, gravite, code_erreur, message, statut, date_resolution)
SELECT v.vin, 'catalogue', NULL, 'Profil', f.id_doublon::text || ' (' || v.genre || ')', f.id_conserve::text,
       'info', 'FUSIONNE_DOUBLON', 'Profil fusionné le 07/10/2026 (lot 3) : identique après rattachement au lexique',
       'resolu', now()
  FROM _fusion f JOIN catalogue.vehicule_catalogue v ON v.id_vehicule_catalogue = f.id_doublon;
UPDATE catalogue.vehicule_source s SET id_vehicule_catalogue = f.id_conserve
  FROM _fusion f WHERE s.id_vehicule_catalogue = f.id_doublon;
DELETE FROM catalogue.vehicule_catalogue WHERE id_vehicule_catalogue IN (SELECT id_doublon FROM _fusion);

\echo '=== 5. Suppression du libellé libre et nouvelle unicité ==='
DROP VIEW catalogue.vehicules_catalogue;
ALTER TABLE catalogue.vehicule_catalogue DROP CONSTRAINT vehicule_catalogue_vin_marque_modele_genre_energie_puissan_key;
ALTER TABLE catalogue.vehicule_catalogue ALTER COLUMN id_terme_vehicule SET NOT NULL;
ALTER TABLE catalogue.vehicule_catalogue DROP COLUMN genre;
ALTER TABLE catalogue.vehicule_catalogue ADD CONSTRAINT vehicule_catalogue_profil_key
  UNIQUE NULLS NOT DISTINCT (vin, marque, modele, id_terme_vehicule, avec_remorque, avec_double_commande,
                             avec_double_cabine, code_categorie_suggeree, energie, puissance, charge_utile, nombre_places);
CREATE INDEX idx_vehicule_catalogue_id_terme_vehicule ON catalogue.vehicule_catalogue (id_terme_vehicule);

\echo '=== 6. Vues ==='
CREATE VIEW catalogue.profil_vehicule AS
SELECT v.id_vehicule_catalogue, v.vin, v.wmi, v.marque, v.modele,
       g.libelle AS genre, t.libelle AS terme_vehicule, v.code_categorie_suggeree,
       v.avec_remorque, v.avec_double_commande, v.avec_double_cabine,
       v.energie, v.puissance, v.charge_utile, v.nombre_places, v.taille_vin, v.date_creation, v.id_terme_vehicule
  FROM catalogue.vehicule_catalogue v
  JOIN referentiel.terme_vehicule t USING (id_terme_vehicule)
  JOIN tarification.genre g ON g.id_genre = t.id_genre;
COMMENT ON VIEW catalogue.profil_vehicule IS 'Profil de véhicule lu par l API : genre canonique, terme, attributs, catégorie suggérée.';

CREATE VIEW catalogue.vehicules_catalogue AS
SELECT id_vehicule_catalogue AS id, vin, wmi, marque, modele, genre, energie, puissance,
       charge_utile, nombre_places, taille_vin, date_creation
  FROM catalogue.profil_vehicule;
COMMENT ON VIEW catalogue.vehicules_catalogue IS
  'TRANSITOIRE (07/10/2026) : ancien nom pour un server.js non corrigé. À supprimer après réconciliation Git.';

GRANT SELECT ON catalogue.profil_vehicule, catalogue.vehicules_catalogue TO mutuellepro;
GRANT SELECT ON referentiel.correspondance_libelle_vehicule TO mutuellepro;
GRANT EXECUTE ON FUNCTION referentiel.fn_normaliser_libelle(text) TO mutuellepro;

\echo '=== 7. Contrôles ==='
DO $k$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM catalogue.vehicule_catalogue WHERE id_terme_vehicule IS NULL;
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  % profil(s) sans terme', n; END IF;
  SELECT count(*) INTO n FROM catalogue.vehicule_catalogue v
   WHERE NOT EXISTS (SELECT 1 FROM catalogue.vehicule_source s WHERE s.id_vehicule_catalogue = v.id_vehicule_catalogue);
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  % profil(s) sans source', n; END IF;
  IF NOT has_table_privilege('mutuellepro', 'catalogue.profil_vehicule', 'SELECT') THEN
    RAISE EXCEPTION '[ÉCHEC]  droit de lecture manquant sur catalogue.profil_vehicule';
  END IF;
  RAISE NOTICE '[OK]     Tous les profils rattachés à un terme, sources intactes, droits accordés';
END $k$;

SELECT 'avant' AS etat, profils, sources, anomalies FROM _volumes_avant
UNION ALL
SELECT 'après', (SELECT count(*) FROM catalogue.vehicule_catalogue), (SELECT count(*) FROM catalogue.vehicule_source),
       (SELECT count(*) FROM catalogue.anomalie_fusion);

\echo '--- Exemples ---'
SELECT vin, marque, modele, genre, terme_vehicule, code_categorie_suggeree AS cat, avec_remorque AS rem,
       avec_double_commande AS dco, avec_double_cabine AS dcab
  FROM catalogue.profil_vehicule
 WHERE vin IN ('JT1E0CE9000048953', '1C4GHB4R2RU509752') OR terme_vehicule IN ('Moto-taxi', 'Voirie')
 ORDER BY terme_vehicule, vin LIMIT 12;

\echo '=== Fin ==='
\if :commit
  COMMIT;
  \echo '>>> VALIDÉ : catalogue rattaché au lexique.'
\else
  ROLLBACK;
  \echo '>>> ESSAI À BLANC : tout a été annulé. Relancer avec -v commit=true pour appliquer.'
\endif
