-- =====================================================================
-- Phase site — Lot S4 (07/10/2026) : regroupement des jetons et des codes
--   8 tables -> site.nature_jeton (natures et durées), site.jeton, site.code_verification
--   * activation_staff_tokens, activation_partenaire_tokens        -> jeton ACTIVATION (72 h)
--   * reinitialisation_mdp_tokens, tokens_reinitialisation_mdp     -> jeton REINITIALISATION_MDP (1 h)
--   * verification_email_tokens                                    -> jeton VERIFICATION_EMAIL (48 h)
--   * tokens_reinitialisation_boite_mail                           -> jeton REINITIALISATION_BOITE_MAIL (1 h)
--   * codes_verification_connexion                                 -> code CONNEXION (10 min)
--   * suivi_ticket_codes                                           -> code SUIVI_TICKET (10 min)
--   Date d'expiration calculée d'après la nature ; déclencheurs de suppression des jetons d'un
--   compte supprimé ; fonction de purge quotidienne des jetons et codes expirés.
--
--   essai à blanc : sudo -u postgres psql -d vpiclist -P pager=off -v ON_ERROR_STOP=1 -v commit=false -f /tmp/lot_s4_jetons.sql
--   application   : sudo -u postgres psql -d vpiclist -P pager=off -v ON_ERROR_STOP=1 -v commit=true  -f /tmp/lot_s4_jetons.sql
-- =====================================================================
\set QUIET on
\set VERBOSITY terse
\pset footer off
BEGIN;

\echo '=== 0. État initial et types de compte rencontrés ==='
CREATE TEMP TABLE _avant AS
SELECT (SELECT count(*) FROM site.activation_staff_tokens) + (SELECT count(*) FROM site.activation_partenaire_tokens)
     + (SELECT count(*) FROM site.reinitialisation_mdp_tokens) + (SELECT count(*) FROM site.tokens_reinitialisation_mdp)
     + (SELECT count(*) FROM site.verification_email_tokens) + (SELECT count(*) FROM site.tokens_reinitialisation_boite_mail) AS jetons,
       (SELECT count(*) FROM site.codes_verification_connexion) + (SELECT count(*) FROM site.suivi_ticket_codes) AS codes;
SELECT * FROM _avant;
SELECT 'tokens_reinitialisation_mdp' AS source, type_compte, count(*) FROM site.tokens_reinitialisation_mdp GROUP BY 2
UNION ALL SELECT 'tokens_reinitialisation_boite_mail', type_compte, count(*) FROM site.tokens_reinitialisation_boite_mail GROUP BY 2
UNION ALL SELECT 'codes_verification_connexion', type_compte, count(*) FROM site.codes_verification_connexion GROUP BY 2
ORDER BY 1, 2;

\echo '=== 1. Natures et tables ==='
CREATE TABLE site.nature_jeton (
  code_nature_jeton varchar(30) PRIMARY KEY,
  libelle           varchar(100) NOT NULL,
  famille           varchar(5) NOT NULL CHECK (famille IN ('JETON', 'CODE')),
  duree_validite    interval NOT NULL
);
COMMENT ON TABLE site.nature_jeton IS 'Natures de jetons et de codes à usage unique, avec leur durée de validité (lot S4, 07/10/2026).';
INSERT INTO site.nature_jeton VALUES
  ('ACTIVATION',                  'Activation d''un compte',                              'JETON', interval '72 hours'),
  ('REINITIALISATION_MDP',        'Réinitialisation du mot de passe',                     'JETON', interval '1 hour'),
  ('VERIFICATION_EMAIL',          'Vérification de l''adresse électronique',              'JETON', interval '48 hours'),
  ('REINITIALISATION_BOITE_MAIL', 'Réinitialisation du mot de passe de la boîte mail',    'JETON', interval '1 hour'),
  ('CONNEXION',                   'Code de vérification à la connexion',                  'CODE',  interval '10 minutes'),
  ('SUIVI_TICKET',                'Code de suivi d''un ticket',                           'CODE',  interval '10 minutes');

CREATE TABLE site.jeton (
  token             varchar(64) PRIMARY KEY,
  code_nature_jeton varchar(30) NOT NULL REFERENCES site.nature_jeton (code_nature_jeton),
  type_compte       varchar(12) NOT NULL CHECK (type_compte IN ('client', 'staff', 'partenaire')),
  id_compte         integer NOT NULL,
  date_creation     timestamptz NOT NULL DEFAULT now(),
  date_expiration   timestamptz NOT NULL
);
CREATE INDEX jeton_type_compte_id_compte_code_nature_jeton_idx ON site.jeton (type_compte, id_compte, code_nature_jeton);
CREATE INDEX jeton_date_expiration_idx ON site.jeton (date_expiration);
COMMENT ON TABLE site.jeton IS 'Jetons à usage unique envoyés par lien (activation, réinitialisation, vérification).';

CREATE TABLE site.code_verification (
  id_code_verification integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_nature_jeton    varchar(30) NOT NULL REFERENCES site.nature_jeton (code_nature_jeton),
  type_compte          varchar(12) CHECK (type_compte IN ('client', 'staff', 'partenaire')),
  id_compte            integer,
  identifiant          varchar(255),
  code                 varchar(6) NOT NULL,
  date_creation        timestamptz NOT NULL DEFAULT now(),
  date_expiration      timestamptz NOT NULL,
  tentatives           integer NOT NULL DEFAULT 0,
  utilise              boolean NOT NULL DEFAULT false,
  CHECK ((type_compte IS NOT NULL AND id_compte IS NOT NULL) OR identifiant IS NOT NULL)
);
CREATE INDEX code_verification_code_nature_jeton_type_compte_id_compte_idx ON site.code_verification (code_nature_jeton, type_compte, id_compte);
CREATE INDEX code_verification_code_nature_jeton_identifiant_idx ON site.code_verification (code_nature_jeton, identifiant);
CREATE INDEX code_verification_date_expiration_idx ON site.code_verification (date_expiration);
COMMENT ON TABLE site.code_verification IS 'Codes à usage unique (connexion, suivi de ticket), avec tentatives.';

\echo '=== 2. Expiration d après la nature, suppression avec le compte, purge ==='
CREATE FUNCTION site.fn_jeton_date_expiration() RETURNS trigger LANGUAGE plpgsql AS $f$
BEGIN
  IF NEW.date_expiration IS NULL THEN
    SELECT now() + duree_validite INTO NEW.date_expiration
      FROM site.nature_jeton WHERE code_nature_jeton = NEW.code_nature_jeton;
  END IF;
  RETURN NEW;
END $f$;
CREATE TRIGGER trg_jeton_date_expiration BEFORE INSERT ON site.jeton
  FOR EACH ROW EXECUTE FUNCTION site.fn_jeton_date_expiration();
CREATE TRIGGER trg_code_verification_date_expiration BEFORE INSERT ON site.code_verification
  FOR EACH ROW EXECUTE FUNCTION site.fn_jeton_date_expiration();

-- arguments : type de compte, nom de la colonne identifiant du compte
CREATE FUNCTION site.fn_supprimer_jetons_compte() RETURNS trigger LANGUAGE plpgsql AS $f$
DECLARE v_id integer := (to_jsonb(OLD) ->> TG_ARGV[1])::integer;
BEGIN
  DELETE FROM site.jeton WHERE type_compte = TG_ARGV[0] AND id_compte = v_id;
  DELETE FROM site.code_verification WHERE type_compte = TG_ARGV[0] AND id_compte = v_id;
  RETURN OLD;
END $f$;
CREATE TRIGGER trg_supprimer_jetons_compte AFTER DELETE ON site.utilisateurs
  FOR EACH ROW EXECUTE FUNCTION site.fn_supprimer_jetons_compte('client', 'id_utilisateur');
CREATE TRIGGER trg_supprimer_jetons_compte AFTER DELETE ON site.staff
  FOR EACH ROW EXECUTE FUNCTION site.fn_supprimer_jetons_compte('staff', 'id_staff');
CREATE TRIGGER trg_supprimer_jetons_compte AFTER DELETE ON site.partenaires
  FOR EACH ROW EXECUTE FUNCTION site.fn_supprimer_jetons_compte('partenaire', 'id_partenaire');

CREATE FUNCTION site.fn_purger_jetons_expires() RETURNS text LANGUAGE plpgsql AS $f$
DECLARE nj int; nc int;
BEGIN
  DELETE FROM site.jeton WHERE date_expiration < now();
  GET DIAGNOSTICS nj = ROW_COUNT;
  -- les codes sont gardés un jour après expiration (trace des tentatives)
  DELETE FROM site.code_verification WHERE date_expiration < now() - interval '1 day';
  GET DIAGNOSTICS nc = ROW_COUNT;
  RETURN format('%s : %s jeton(s) et %s code(s) expiré(s) purgé(s)', to_char(now(), 'YYYY-MM-DD HH24:MI'), nj, nc);
END $f$;
COMMENT ON FUNCTION site.fn_purger_jetons_expires() IS 'Purge quotidienne (tâche de nuit) des jetons et codes expirés.';

\echo '=== 3. Reprise des données ==='
INSERT INTO site.jeton (token, code_nature_jeton, type_compte, id_compte, date_creation, date_expiration)
SELECT token, 'ACTIVATION', 'staff', id_staff, date_creation, date_expiration FROM site.activation_staff_tokens
UNION ALL SELECT token, 'ACTIVATION', 'partenaire', id_partenaire, date_creation, date_expiration FROM site.activation_partenaire_tokens
UNION ALL SELECT token, 'REINITIALISATION_MDP', 'client', id_utilisateur, date_creation, date_expiration FROM site.reinitialisation_mdp_tokens
UNION ALL SELECT token, 'REINITIALISATION_MDP', type_compte, id_compte, date_creation, date_expiration FROM site.tokens_reinitialisation_mdp
UNION ALL SELECT token, 'VERIFICATION_EMAIL', 'client', id_utilisateur, date_creation, date_expiration FROM site.verification_email_tokens
UNION ALL SELECT token, 'REINITIALISATION_BOITE_MAIL', type_compte, id_compte, date_creation, date_expiration FROM site.tokens_reinitialisation_boite_mail;

INSERT INTO site.code_verification (code_nature_jeton, type_compte, id_compte, identifiant, code, date_creation, date_expiration, tentatives, utilise)
SELECT 'CONNEXION', type_compte, id_compte, NULL, code, date_creation, date_expiration, tentatives, utilise FROM site.codes_verification_connexion
UNION ALL
SELECT 'SUIVI_TICKET', NULL, NULL, identifiant, code, date_creation, date_expiration, tentatives, utilise FROM site.suivi_ticket_codes;

\echo '=== 4. Suppression des huit anciennes tables ==='
DROP TABLE site.activation_staff_tokens, site.activation_partenaire_tokens, site.reinitialisation_mdp_tokens,
           site.tokens_reinitialisation_mdp, site.verification_email_tokens, site.tokens_reinitialisation_boite_mail,
           site.codes_verification_connexion, site.suivi_ticket_codes;

GRANT SELECT ON site.nature_jeton TO mutuellepro;
GRANT SELECT, INSERT, UPDATE, DELETE ON site.jeton, site.code_verification TO mutuellepro;
GRANT USAGE ON SEQUENCE site.code_verification_id_code_verification_seq TO mutuellepro;
GRANT EXECUTE ON FUNCTION site.fn_purger_jetons_expires() TO mutuellepro;

\echo '=== 5. Contrôles ==='
DO $k$
DECLARE n int; d timestamptz; v_id int;
BEGIN
  IF (SELECT count(*) FROM site.jeton) <> (SELECT jetons FROM _avant)
     OR (SELECT count(*) FROM site.code_verification) <> (SELECT codes FROM _avant) THEN
    RAISE EXCEPTION '[ÉCHEC]  volumes repris différents des volumes d origine';
  END IF;
  -- l'expiration se calcule d'après la nature
  INSERT INTO site.jeton (token, code_nature_jeton, type_compte, id_compte) VALUES ('__test__', 'ACTIVATION', 'staff', -1)
  RETURNING date_expiration INTO d;
  IF d < now() + interval '71 hours' OR d > now() + interval '73 hours' THEN RAISE EXCEPTION '[ÉCHEC]  durée d activation incorrecte'; END IF;
  DELETE FROM site.jeton WHERE token = '__test__';
  INSERT INTO site.code_verification (code_nature_jeton, identifiant, code) VALUES ('SUIVI_TICKET', '__test__', '000000')
  RETURNING id_code_verification, date_expiration INTO v_id, d;
  IF d > now() + interval '11 minutes' THEN RAISE EXCEPTION '[ÉCHEC]  durée de code incorrecte'; END IF;
  DELETE FROM site.code_verification WHERE id_code_verification = v_id;
  SELECT count(*) INTO n FROM pg_class WHERE relnamespace = 'site'::regnamespace
     AND relname ~ '(_tokens|tokens_|codes_verification_connexion|suivi_ticket_codes)';
  IF n > 0 THEN RAISE EXCEPTION '[ÉCHEC]  % ancien(s) objet(s) restant(s)', n; END IF;
  IF NOT has_table_privilege('mutuellepro', 'site.jeton', 'INSERT')
     OR NOT has_table_privilege('mutuellepro', 'site.code_verification', 'UPDATE') THEN
    RAISE EXCEPTION '[ÉCHEC]  droits de mutuellepro manquants';
  END IF;
  RAISE NOTICE '[OK]     Données reprises à l identique, durées calculées, anciennes tables supprimées, droits accordés';
END $k$;

SELECT 'avant' AS etat, jetons, codes FROM _avant
UNION ALL SELECT 'après', (SELECT count(*) FROM site.jeton), (SELECT count(*) FROM site.code_verification);
SELECT code_nature_jeton, type_compte, count(*) FROM site.jeton GROUP BY 1, 2
UNION ALL SELECT code_nature_jeton, coalesce(type_compte, '(identifiant)'), count(*) FROM site.code_verification GROUP BY 1, 2
ORDER BY 1, 2;
SELECT site.fn_purger_jetons_expires() AS purge_simulee;

\echo '=== Fin ==='
\if :commit
  COMMIT;
  \echo '>>> VALIDÉ : jetons regroupés. Appliquer AUSSITÔT le correctif du code (patch_s4.sh).'
\else
  ROLLBACK;
  \echo '>>> ESSAI À BLANC : tout a été annulé. Relancer avec -v commit=true pour appliquer.'
\endif
